/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package McDonaldsDriveThrough;

import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;

/**
 *
 * @author Anta
 */
public class MCDrive extends javax.swing.JFrame {

    /**
     * Creates new form MCDrive
     */
    private OrderQueue oq = new OrderQueue();
    
    //Drugi nacin
    private Queue<Order> orderQueue = new LinkedList<>();
    
    
    public MCDrive() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonSizeM = new javax.swing.JRadioButton();
        jRadioButtonSizeS = new javax.swing.JRadioButton();
        jRadioButtonSizeL = new javax.swing.JRadioButton();
        jComboBoxMeal = new javax.swing.JComboBox<>();
        jButtonDeliverOrder = new javax.swing.JButton();
        jButtonOrderNow = new javax.swing.JButton();
        jButtonCheckOrders = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButtonSizeM);
        jRadioButtonSizeM.setText("Size M");

        buttonGroup1.add(jRadioButtonSizeS);
        jRadioButtonSizeS.setText("Size S");

        buttonGroup1.add(jRadioButtonSizeL);
        jRadioButtonSizeL.setText("Size L ");

        jComboBoxMeal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BigMacMeal", "HappyMeal" }));
        jComboBoxMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMealActionPerformed(evt);
            }
        });

        jButtonDeliverOrder.setText("Deliver order");
        jButtonDeliverOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeliverOrderActionPerformed(evt);
            }
        });

        jButtonOrderNow.setText("Order now");
        jButtonOrderNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderNowActionPerformed(evt);
            }
        });

        jButtonCheckOrders.setText("Check Orders");
        jButtonCheckOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jComboBoxMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonSizeL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCheckOrders))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButtonSizeS)
                                    .addComponent(jRadioButtonSizeM))
                                .addGap(47, 47, 47)
                                .addComponent(jButtonOrderNow, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                                .addComponent(jButtonDeliverOrder)))
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSizeS)
                    .addComponent(jComboBoxMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeliverOrder)
                    .addComponent(jButtonOrderNow, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jRadioButtonSizeM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSizeL)
                .addGap(18, 18, 18)
                .addComponent(jButtonCheckOrders)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMealActionPerformed

    private void jButtonDeliverOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeliverOrderActionPerformed
        try{
            System.out.println("Delivered :>>>> " + oq.deliverOrder());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"All orders are completed");
        }
    }//GEN-LAST:event_jButtonDeliverOrderActionPerformed

    private void jButtonOrderNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderNowActionPerformed
        oq.orderNumberCount();
        
        if(jRadioButtonSizeS.isSelected()){
            oq.addOrder(jComboBoxMeal.getSelectedItem().toString(), 'S');
        }else if (jRadioButtonSizeM.isSelected()){
            oq.addOrder(jComboBoxMeal.getSelectedItem().toString(), 'M');
        }else{
            oq.addOrder(jComboBoxMeal.getSelectedItem().toString(), 'L');
        }
        
        System.out.println("Order with number : " + oq.getOrderNumber() + " is set!");

    }//GEN-LAST:event_jButtonOrderNowActionPerformed

    private void jButtonCheckOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckOrdersActionPerformed
        for(Order o : oq.getOrderQueue()){
            System.out.println(o.toString());
        }
    }//GEN-LAST:event_jButtonCheckOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MCDrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MCDrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MCDrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MCDrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MCDrive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCheckOrders;
    private javax.swing.JButton jButtonDeliverOrder;
    private javax.swing.JButton jButtonOrderNow;
    private javax.swing.JComboBox<String> jComboBoxMeal;
    private javax.swing.JRadioButton jRadioButtonSizeL;
    private javax.swing.JRadioButton jRadioButtonSizeM;
    private javax.swing.JRadioButton jRadioButtonSizeS;
    // End of variables declaration//GEN-END:variables
}
