/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package McDonaldsDriveThrough;

import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author Anta
 */
public class UIMcDRIVE extends javax.swing.JFrame {
    
    int orderCount;
    Queue<Meal> Orders = new LinkedList<>();
    

    /**
     * Creates new form UIMcDRIVE
     */
    public UIMcDRIVE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonSmallBigMac = new javax.swing.JRadioButton();
        jRadioButtonLargeBigMac = new javax.swing.JRadioButton();
        jRadioButtonMediumBigMac = new javax.swing.JRadioButton();
        jButtonOrder = new javax.swing.JButton();
        jButtonDeliver = new javax.swing.JButton();
        jButtonCheckOrders = new javax.swing.JButton();
        jButtonOrder2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelMealToOrder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chose youe meal:");

        jLabel2.setText("Order meal");

        jLabel3.setText("Deliver Meal");

        buttonGroup1.add(jRadioButtonSmallBigMac);
        jRadioButtonSmallBigMac.setText("Small BigMac");
        jRadioButtonSmallBigMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSmallBigMacActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonLargeBigMac);
        jRadioButtonLargeBigMac.setText("Large BigMac");

        buttonGroup1.add(jRadioButtonMediumBigMac);
        jRadioButtonMediumBigMac.setText("Medium BigMac");

        jButtonOrder.setText("Order now");
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });

        jButtonDeliver.setText("Deliver now");
        jButtonDeliver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeliverActionPerformed(evt);
            }
        });

        jButtonCheckOrders.setText("Check Orders");
        jButtonCheckOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckOrdersActionPerformed(evt);
            }
        });

        jButtonOrder2.setText("Order now 2");
        jButtonOrder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrder2ActionPerformed(evt);
            }
        });

        jButton1.setText("Small BigMac");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Medium BigMac");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Large BigMac");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelMealToOrder.setText("---------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonSmallBigMac)
                            .addComponent(jRadioButtonLargeBigMac)
                            .addComponent(jRadioButtonMediumBigMac)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonOrder))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCheckOrders)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonDeliver))
                                .addGap(98, 98, 98))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabelMealToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonOrder2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSmallBigMac)
                            .addComponent(jButtonDeliver)))
                    .addComponent(jButtonOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonMediumBigMac)
                .addGap(13, 13, 13)
                .addComponent(jRadioButtonLargeBigMac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOrder2)
                    .addComponent(jButton1)
                    .addComponent(jLabelMealToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(5, 5, 5)
                .addComponent(jButtonCheckOrders)
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        this.orderCount++;
        if(jRadioButtonSmallBigMac.isSelected()){
            System.out.println("Selecet Small");
            Meal meal = new Meal(400,"BigMacSmall",'s',orderCount);
            Orders.add(meal);
            jRadioButtonSmallBigMac.setSelected(false);
        }else if(jRadioButtonMediumBigMac.isSelected()){
            System.out.println("Selecet Medium");
            Meal meal = new Meal(500,"BigMacMedium",'M',orderCount);
            Orders.add(meal);
            jRadioButtonMediumBigMac.setSelected(false);          
        }else{
            System.out.println("Selecet Large");
            Meal meal = new Meal(550,"BigMacLarge",'L',orderCount);
            Orders.add(meal);
            jRadioButtonLargeBigMac.setSelected(false);              
        }
        System.out.println("Order with number : " + orderCount + " is set!");
        
    }//GEN-LAST:event_jButtonOrderActionPerformed

    private void jButtonDeliverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeliverActionPerformed
        try{
            System.out.println("Delivered :>>>> " + Orders.remove());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"All orders are completed");
        } 
    }//GEN-LAST:event_jButtonDeliverActionPerformed

    private void jButtonCheckOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckOrdersActionPerformed
        for(Meal m : Orders){
            System.out.println(m.toString());
        }
    }//GEN-LAST:event_jButtonCheckOrdersActionPerformed

    private void jRadioButtonSmallBigMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSmallBigMacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSmallBigMacActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabelMealToOrder.setText("BigMacSmall");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabelMealToOrder.setText("BigMacMedium");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jLabelMealToOrder.setText("BigMacLarge");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonOrder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrder2ActionPerformed
        this.orderCount++;
        if(jLabelMealToOrder.getText().equals("BigMacSmall")){
            System.out.println("Selecet Small");
            Meal meal = new Meal(400,"BigMacSmall",'s',orderCount);
            Orders.add(meal);
        }else if(jLabelMealToOrder.getText().equals("BigMacMedium")){
            System.out.println("Selecet Medium");
            Meal meal = new Meal(500,"BigMacMedium",'M',orderCount);
            Orders.add(meal);        
        }else if(jLabelMealToOrder.getText().equals("BigMacLarge")){
            System.out.println("Selecet Large");
            Meal meal = new Meal(550,"BigMacLarge",'L',orderCount);
            Orders.add(meal);                
        }
        System.out.println("Order with number : " + orderCount + " is set!");
    }//GEN-LAST:event_jButtonOrder2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIMcDRIVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIMcDRIVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIMcDRIVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIMcDRIVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIMcDRIVE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCheckOrders;
    private javax.swing.JButton jButtonDeliver;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JButton jButtonOrder2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMealToOrder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonLargeBigMac;
    private javax.swing.JRadioButton jRadioButtonMediumBigMac;
    private javax.swing.JRadioButton jRadioButtonSmallBigMac;
    // End of variables declaration//GEN-END:variables
}
