/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrameAndSmile;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Anta
 */
public class JFrameSmile extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSmile
     */
    ImageIcon dizzy;
    ImageIcon nervous;
    ImageIcon pain;
    ImageIcon smile;
    
    public JFrameSmile() {
        initComponents();
        dizzy = new ImageIcon(new ImageIcon("C:\\Users\\Anta\\Desktop\\Images\\dizzy.png")
                .getImage().getScaledInstance(jLabelSmile.getWidth(), jLabelSmile.getWidth(), Image.SCALE_DEFAULT));
        nervous = new ImageIcon(new ImageIcon("C:\\Users\\Anta\\Desktop\\Images\\nervous.png")
                .getImage().getScaledInstance(jLabelSmile.getWidth(), jLabelSmile.getWidth(), Image.SCALE_DEFAULT));
        pain = new ImageIcon(new ImageIcon("C:\\Users\\Anta\\Desktop\\Images\\pain.png")
                .getImage().getScaledInstance(jLabelSmile.getWidth(), jLabelSmile.getWidth(), Image.SCALE_DEFAULT));
        smile = new ImageIcon(new ImageIcon("C:\\Users\\Anta\\Desktop\\Images\\smile.png")
                .getImage().getScaledInstance(jLabelSmile.getWidth(), jLabelSmile.getWidth(), Image.SCALE_DEFAULT));
        jLabelSmile.setIcon(smile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSmile = new javax.swing.JLabel();
        jButtonHeal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSmile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSmileMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSmileMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelSmileMouseReleased(evt);
            }
        });

        jButtonHeal.setText("Heal");
        jButtonHeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHealMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jButtonHeal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabelSmile, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelSmile, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButtonHeal)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jLabelSmileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSmileMouseEntered
        jLabelSmile.setIcon(nervous);
    }//GEN-LAST:event_jLabelSmileMouseEntered

    private void jLabelSmileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSmileMousePressed
        jLabelSmile.setIcon(pain);
    }//GEN-LAST:event_jLabelSmileMousePressed

    private void jLabelSmileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSmileMouseReleased
        jLabelSmile.setIcon(dizzy);
    }//GEN-LAST:event_jLabelSmileMouseReleased

    private void jButtonHealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHealMouseClicked
        jLabelSmile.setIcon(smile);
    }//GEN-LAST:event_jButtonHealMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSmile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSmile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSmile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSmile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSmile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHeal;
    private javax.swing.JLabel jLabelSmile;
    // End of variables declaration//GEN-END:variables
}
