/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author Anta
 */
public class JFrameKalkulator extends javax.swing.JFrame {


    double first;
    double second;
    double result;
    String operator;
    String answer;
    
    public JFrameKalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b = new javax.swing.JButton();
        c = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        nulanula = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        devet = new javax.swing.JButton();
        osam = new javax.swing.JButton();
        sedam = new javax.swing.JButton();
        puta = new javax.swing.JButton();
        sest = new javax.swing.JButton();
        pet = new javax.swing.JButton();
        cetri = new javax.swing.JButton();
        podeljeno = new javax.swing.JButton();
        tri = new javax.swing.JButton();
        dva = new javax.swing.JButton();
        jedan = new javax.swing.JButton();
        modul = new javax.swing.JButton();
        jednako = new javax.swing.JButton();
        tacka = new javax.swing.JButton();
        nula = new javax.swing.JButton();
        jLabelInterface = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        b.setText("<");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        c.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        c.setText("C");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        plus.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        nulanula.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        nulanula.setText("00");

        minus.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        devet.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        devet.setText("9");
        devet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devetActionPerformed(evt);
            }
        });

        osam.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        osam.setText("8");
        osam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osamActionPerformed(evt);
            }
        });

        sedam.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        sedam.setText("7");
        sedam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedamActionPerformed(evt);
            }
        });

        puta.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        puta.setText("*");
        puta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putaActionPerformed(evt);
            }
        });

        sest.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        sest.setText("6");
        sest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sestActionPerformed(evt);
            }
        });

        pet.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        pet.setText("5");
        pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petActionPerformed(evt);
            }
        });

        cetri.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        cetri.setText("4");
        cetri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetriActionPerformed(evt);
            }
        });

        podeljeno.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        podeljeno.setText("/");
        podeljeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                podeljenoActionPerformed(evt);
            }
        });

        tri.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        tri.setText("3");
        tri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triActionPerformed(evt);
            }
        });

        dva.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        dva.setText("2");
        dva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvaActionPerformed(evt);
            }
        });

        jedan.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jedan.setText("1");
        jedan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jedanActionPerformed(evt);
            }
        });

        modul.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        modul.setText("%");
        modul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulActionPerformed(evt);
            }
        });

        jednako.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jednako.setText("=");
        jednako.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jednakoActionPerformed(evt);
            }
        });

        tacka.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        tacka.setText(".");
        tacka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tackaActionPerformed(evt);
            }
        });

        nula.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        nula.setText("0");
        nula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nulaActionPerformed(evt);
            }
        });

        jLabelInterface.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nulanula, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sedam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(osam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(devet, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cetri, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pet, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sest, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jedan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dva, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tri, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(podeljeno, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nula, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tacka, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jednako, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modul, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nulanula, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sedam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(osam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(devet, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cetri, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sest, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jedan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dva, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(podeljeno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tri, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nula, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tacka, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modul, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jednako, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cetriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetriActionPerformed
        jLabelInterface.setText(jLabelInterface.getText() + cetri.getText());
    }//GEN-LAST:event_cetriActionPerformed

    private void nulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nulaActionPerformed
        jLabelInterface.setText(jLabelInterface.getText() + nula.getText());
    }//GEN-LAST:event_nulaActionPerformed

    private void tackaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tackaActionPerformed
        jLabelInterface.setText(jLabelInterface.getText() + tacka.getText());
    }//GEN-LAST:event_tackaActionPerformed

    private void dvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvaActionPerformed
        jLabelInterface.setText(jLabelInterface.getText() + dva.getText());
    }//GEN-LAST:event_dvaActionPerformed

    private void triActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triActionPerformed
        jLabelInterface.setText(jLabelInterface.getText() + tri.getText());
    }//GEN-LAST:event_triActionPerformed

    private void petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petActionPerformed
        jLabelInterface.setText(jLabelInterface.getText() + pet.getText());
    }//GEN-LAST:event_petActionPerformed

    private void sestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sestActionPerformed
        jLabelInterface.setText(jLabelInterface.getText() + sest.getText());
    }//GEN-LAST:event_sestActionPerformed

    private void sedamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedamActionPerformed
        jLabelInterface.setText(jLabelInterface.getText() + sedam.getText());
    }//GEN-LAST:event_sedamActionPerformed

    private void osamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osamActionPerformed
        jLabelInterface.setText(jLabelInterface.getText() + osam.getText());
    }//GEN-LAST:event_osamActionPerformed

    private void devetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devetActionPerformed
        jLabelInterface.setText(jLabelInterface.getText() + devet.getText());
    }//GEN-LAST:event_devetActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        jLabelInterface.setText("");
    }//GEN-LAST:event_cActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        String backSpace = null;
        String kalkulatorInterface = jLabelInterface.getText();
        if(kalkulatorInterface.length() > 0){
            backSpace = kalkulatorInterface.substring(0, kalkulatorInterface.length() - 1);
            jLabelInterface.setText(backSpace);
        }
    }//GEN-LAST:event_bActionPerformed

    private void jedanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jedanActionPerformed
        jLabelInterface.setText(jLabelInterface.getText() + jedan.getText());
    }//GEN-LAST:event_jedanActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        first=Double.parseDouble(jLabelInterface.getText());
        jLabelInterface.setText("");
        operator="+";
    }//GEN-LAST:event_plusActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        first=Double.parseDouble(jLabelInterface.getText());
        jLabelInterface.setText("");
        operator="-";
    }//GEN-LAST:event_minusActionPerformed

    private void putaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putaActionPerformed
        first=Double.parseDouble(jLabelInterface.getText());
        jLabelInterface.setText("");
        operator="*";
    }//GEN-LAST:event_putaActionPerformed

    private void podeljenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_podeljenoActionPerformed
        first=Double.parseDouble(jLabelInterface.getText());
        jLabelInterface.setText("");
        operator="/";
    }//GEN-LAST:event_podeljenoActionPerformed

    private void modulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulActionPerformed
        first=Double.parseDouble(jLabelInterface.getText());
        jLabelInterface.setText("");
        operator="%";
    }//GEN-LAST:event_modulActionPerformed

    private void jednakoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jednakoActionPerformed
        second = Double.parseDouble(jLabelInterface.getText());
        switch(operator){
            case "+":
                result = first + second;
//                jLabelInterface.setText(String.format("%.2f", result));
                jLabelInterface.setText(String.valueOf(result));
                break;
            case "-":
                result = first - second;
                jLabelInterface.setText(String.valueOf(result));
                break;
            case "*":
                result = first * second;
                jLabelInterface.setText(String.valueOf(result));
                break;
            case "/":
                result = first / second;
                jLabelInterface.setText(String.valueOf(result));
                break;
            case "%":
                result = first % second;
                jLabelInterface.setText(String.valueOf(result));
                break;
        }
    }//GEN-LAST:event_jednakoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameKalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JButton cetri;
    private javax.swing.JButton devet;
    private javax.swing.JButton dva;
    private javax.swing.JLabel jLabelInterface;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jedan;
    private javax.swing.JButton jednako;
    private javax.swing.JButton minus;
    private javax.swing.JButton modul;
    private javax.swing.JButton nula;
    private javax.swing.JButton nulanula;
    private javax.swing.JButton osam;
    private javax.swing.JButton pet;
    private javax.swing.JButton plus;
    private javax.swing.JButton podeljeno;
    private javax.swing.JButton puta;
    private javax.swing.JButton sedam;
    private javax.swing.JButton sest;
    private javax.swing.JButton tacka;
    private javax.swing.JButton tri;
    // End of variables declaration//GEN-END:variables
}
